# Generated by Django 2.2.27 on 2022-02-18 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220218_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 2, 18, 14, 10, 47, 636568), verbose_name='Опубликована'),
        ),
    ]
